project:
  task_name: 'eyepacs-dr-classification'
  random_seed: 42


paths:
  root_dir: 'F:/ZPB/dataset/original'
  images_dir: 'F:/ZPB/dataset/original/train'
  labels_csv: 'F:/ZPB/dataset/original/trainLabels.csv'
  results_dir: results
